// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMsPInM58uPksNu3E9iQ5EhnWBz67CPeQ',
    appId: '1:702443834173:web:a4148356cf434a6fda1354',
    messagingSenderId: '702443834173',
    projectId: 'scanpal-f74da',
    authDomain: 'scanpal-f74da.firebaseapp.com',
    databaseURL: 'https://scanpal-f74da.firebaseio.com',
    storageBucket: 'scanpal-f74da.appspot.com',
    measurementId: 'G-37KL0M4ESD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyf50wY-v9ssykgHy8GlbnCyOYPym040I',
    appId: '1:702443834173:android:4e16855889bf6fd5da1354',
    messagingSenderId: '702443834173',
    projectId: 'scanpal-f74da',
    databaseURL: 'https://scanpal-f74da.firebaseio.com',
    storageBucket: 'scanpal-f74da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRF0htEq8Azm3ozQn9my4V7esKRoClwE0',
    appId: '1:702443834173:ios:3e6ae008cd7fc3beda1354',
    messagingSenderId: '702443834173',
    projectId: 'scanpal-f74da',
    databaseURL: 'https://scanpal-f74da.firebaseio.com',
    storageBucket: 'scanpal-f74da.appspot.com',
    androidClientId: '702443834173-1v959753ogu72pl6r3bk2gti9027j4ru.apps.googleusercontent.com',
    iosClientId: '702443834173-r9qoeer5pq91g48gqp08vtmoab1g48q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fikisha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRF0htEq8Azm3ozQn9my4V7esKRoClwE0',
    appId: '1:702443834173:ios:3e6ae008cd7fc3beda1354',
    messagingSenderId: '702443834173',
    projectId: 'scanpal-f74da',
    databaseURL: 'https://scanpal-f74da.firebaseio.com',
    storageBucket: 'scanpal-f74da.appspot.com',
    androidClientId: '702443834173-1v959753ogu72pl6r3bk2gti9027j4ru.apps.googleusercontent.com',
    iosClientId: '702443834173-r9qoeer5pq91g48gqp08vtmoab1g48q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fikisha',
  );
}
